#!/bin/bash

####################################################################################
# Production Deployment Step-by-Step Guide
# 
# Lengkap dan siap untuk diproduksi
# Bacaan untuk admin dan DevOps
####################################################################################

# STEP 0: PRE-DEPLOYMENT PREPARATION
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 0: PRE-DEPLOYMENT PREPARATION"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Checklist:"
echo "  ☐ Backup existing database"
echo "  ☐ Test migration on staging environment"
echo "  ☐ Review all pending migrations"
echo "  ☐ Verify environment variables"
echo "  ☐ Check disk space (minimum 2GB free)"
echo "  ☐ Verify database connection"
echo "  ☐ Notify team about deployment"
echo ""

# STEP 1: RUN PRE-MIGRATION CHECKS
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 1: PRE-MIGRATION CHECKS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Running pre-migration checks and creating backup..."
echo "Command: npm run migration:pre"
echo ""
echo "This will:"
echo "  1. Validate environment variables"
echo "  2. Test database connection"
echo "  3. Create database backup"
echo "  4. Validate Prisma schema"
echo "  5. Check migration status"
echo ""

# STEP 2: APPLY MIGRATIONS
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 2: APPLY MIGRATIONS & SEED"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Applying migrations and seeding production database..."
echo "Command: npm run migration:apply:prod:seed"
echo ""
echo "This will:"
echo "  1. Apply all pending migrations"
echo "  2. Generate Prisma Client"
echo "  3. Seed database with production data (won't overwrite)"
echo "  4. Run verification checks"
echo ""

# STEP 3: BUILD DOCKER IMAGE
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 3: BUILD DOCKER IMAGE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Building production Docker image..."
echo "Command: npm run docker:build:tag"
echo ""
echo "This will:"
echo "  1. Build Docker image with production optimizations"
echo "  2. Tag image with timestamp"
echo "  3. Push to registry (if configured)"
echo ""

# STEP 4: START SERVICES
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 4: START PRODUCTION SERVICES"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Starting Docker Compose services..."
echo "Command: npm run production:start"
echo ""
echo "This will:"
echo "  1. Start MySQL database service"
echo "  2. Start application service"
echo "  3. Perform health checks"
echo ""

# STEP 5: VERIFY DEPLOYMENT
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 5: VERIFY DEPLOYMENT"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Verifying deployment success..."
echo "Commands:"
echo "  # Check service status"
echo "  npm run docker:compose:ps"
echo ""
echo "  # Check logs"
echo "  npm run production:logs"
echo ""
echo "  # Health check"
echo "  npm run production:health"
echo ""
echo "  # Monitor migrations"
echo "  npm run production:monitor"
echo ""

# STEP 6: POST-DEPLOYMENT TESTS
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 6: POST-DEPLOYMENT TESTS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Critical checks after deployment:"
echo ""
echo "  1. Health Check Endpoint"
echo "     curl http://localhost:3000/api/health"
echo ""
echo "  2. Database Connection"
echo "     Verify all tables created: mysql -h 202.74.74.69 -u driver -p driver"
echo ""
echo "  3. API Tests"
echo "     - Login endpoint"
echo "     - Booking creation"
echo "     - Driver status update"
echo "     - GPS tracking"
echo "     - WhatsApp notifications"
echo ""
echo "  4. Application Functionality"
echo "     - Test admin dashboard"
echo "     - Test driver app"
echo "     - Test employee functions"
echo ""

# STEP 7: MONITORING
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 7: CONTINUOUS MONITORING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Monitor logs and performance:"
echo "  # Real-time application logs"
echo "  npm run production:logs"
echo ""
echo "  # Database monitoring"
echo "  npm run production:monitor"
echo ""
echo "  # Check CPU and memory usage"
echo "  docker stats driver_booking_app_prod"
echo ""

# EMERGENCY ROLLBACK
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "EMERGENCY: ROLLBACK PROCEDURE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "If something goes wrong, follow this procedure:"
echo ""
echo "  1. List available backups"
echo "     npm run migration:rollback -- --list"
echo ""
echo "  2. Rollback to specific backup"
echo "     npm run migration:rollback -- backup_pre_migration_20260301_010000.sql"
echo ""
echo "  3. Stop services (if needed)"
echo "     npm run production:stop"
echo ""
echo "  4. Restart services"
echo "     npm run production:start"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "DEPLOYMENT GUIDE COMPLETE"
echo "═══════════════════════════════════════════════════════════════"
