#!/bin/bash

####################################################################################
# 🚀 PRODUCTION DEPLOYMENT - QUICK START GUIDE
# 
# Panduan cepat untuk deployment Prisma migration & seeding ke production Dockploy
####################################################################################

clear

echo ""
echo "╔═══════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                           ║"
echo "║   🚀  PRODUCTION DEPLOYMENT - QUICK START GUIDE  🚀                       ║"
echo "║                                                                           ║"
echo "║   Prisma Migration & Seeding - Production Ready                           ║"
echo "║                                                                           ║"
echo "╚═══════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📚 DOKUMENTASI YANG TELAH DIBUAT:"
echo ""
echo "1️⃣  PRISMA_PRODUCTION_GUIDE.md"
echo "   → Panduan lengkap (190+ baris)"
echo "   → Mencakup semua aspek production deployment"
echo "   → Start di sini untuk pemahaman mendalam"
echo ""

echo "2️⃣  DEPLOYMENT_CHECKLIST.md"
echo "   → Checklist step-by-step"
echo "   → Pre/post deployment verification"
echo "   → Database seeding details"
echo "   → Emergency rollback procedures"
echo ""

echo "3️⃣  DEPLOYMENT_GUIDE.sh (this file)"
echo "   → Visual step-by-step walkthrough"
echo "   → Penjelasan setiap tahap"
echo "   → Commands yang bisa langsung dijalankan"
echo ""

echo "4️⃣  PRODUCTION_DEPLOYMENT_SUMMARY.md"
echo "   → Ringkasan lengkap semua file yang dibuat"
echo "   → File checklist"
echo "   → Quick reference"
echo ""

echo "5️⃣  scripts/README.md"
echo "   → Dokumentasi untuk setiap script"
echo "   → Usage examples"
echo "   → Troubleshooting guide"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "⚙️  SCRIPTS PRODUCTION-READY"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

echo "📋 scripts/pre-migration.sh"
echo "   Validasi sebelum deployment"
echo "   Command: npm run migration:pre"
echo ""

echo "🚀 scripts/apply-migration.sh"
echo "   Apply migrations ke database"
echo "   Command: npm run migration:apply:prod:seed"
echo ""

echo "🔙 scripts/rollback-migration.sh"
echo "   Emergency rollback ke backup sebelumnya"
echo "   Command: npm run migration:rollback -- <backup-file>"
echo ""

echo "📊 scripts/monitor-migration.sh"
echo "   Monitoring dashboard real-time"
echo "   Command: npm run production:monitor"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "⚙️  PRODUCTION CONFIGURATION FILES"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

echo "🐳 Dockerfile.production"
echo "   Multi-stage production Docker image"
echo "   - Alpine-based untuk ukuran kecil"
echo "   - Security best practices"
echo "   - Health checks included"
echo ""

echo "🐳 docker-compose.production.yml"
echo "   Service orchestration"
echo "   - MySQL database service"
echo "   - Next.js application service"
echo "   - Health checks & monitoring"
echo ""

echo "🔧 dockploy.yml"
echo "   Dockploy deployment configuration"
echo "   - Pre/post deploy hooks"
echo "   - Automatic backup & rollback"
echo ""

echo "🌱 prisma/seed-production.ts"
echo "   Production-safe seeding script"
echo "   - Won't overwrite existing data"
echo "   - Optional force mode"
echo ""

echo "📝 .env.production.example"
echo "   Environment template"
echo "   - Copy to .env.production"
echo "   - Fill in your actual values"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "🎯 DEPLOYMENT QUICKSTART"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

echo "STEP 1: Setup Environment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cp .env.production.example .env.production"
echo "  # Edit .env.production dengan credentials database Anda"
echo "  # Minimum yang perlu diubah:"
echo "  #   DATABASE_URL=mysql://driver:your_password@202.74.74.69:3306/driver"
echo "  #   MYSQL_ROOT_PASSWORD=your_root_password"
echo "  #   MYSQL_PASSWORD=your_user_password"
echo "  #   ADMIN_PASSWORD=secure_admin_password"
echo ""

echo "STEP 2: Pre-Deployment Validation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  npm run migration:pre"
echo ""
echo "  ✓ Validasi environment variables"
echo "  ✓ Test database connection"
echo "  ✓ Create automatic backup"
echo "  ✓ Validate Prisma schema"
echo ""

echo "STEP 3: Apply Migrations & Seed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  npm run migration:apply:prod:seed"
echo ""
echo "  ✓ Apply all pending migrations"
echo "  ✓ Generate Prisma Client"
echo "  ✓ Seed production database"
echo "  ✓ Run verification checks"
echo ""

echo "STEP 4: Build Docker Image"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  npm run docker:build:tag"
echo ""
echo "  ✓ Build production image"
echo "  ✓ Tag dengan timestamp"
echo ""

echo "STEP 5: Start Services"
echo "━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  npm run production:start"
echo ""
echo "  ✓ Start MySQL container"
echo "  ✓ Start application container"
echo "  ✓ Health checks passed"
echo ""

echo "STEP 6: Verify & Monitor"
echo "━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  npm run production:monitor"
echo "  npm run production:logs"
echo "  npm run production:health"
echo ""
echo "  ✓ All services healthy"
echo "  ✓ No errors in logs"
echo "  ✓ API responding"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "📋 NPM SCRIPTS REFERENCE"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

echo "PRISMA COMMANDS:"
echo "  npm run prisma:validate              Validate schema"
echo "  npm run prisma:status                Check migration status"
echo "  npm run prisma:generate              Generate Prisma Client"
echo "  npm run prisma:migrate:deploy        Deploy migrations"
echo "  npm run prisma:seed:production       Seed database (safe)"
echo "  npm run prisma:seed:production:force Seed database (force)"
echo ""

echo "MIGRATION COMMANDS:"
echo "  npm run migration:pre                Pre-deployment checks"
echo "  npm run migration:apply              Apply migrations"
echo "  npm run migration:apply:seed         Apply + seed"
echo "  npm run migration:apply:prod         Production apply"
echo "  npm run migration:apply:prod:seed    Production apply + seed"
echo "  npm run migration:rollback           Emergency rollback"
echo "  npm run migration:monitor            Monitoring dashboard"
echo ""

echo "DOCKER COMMANDS:"
echo "  npm run docker:build                 Build image"
echo "  npm run docker:build:tag             Build + tag"
echo "  npm run docker:compose:up            Start services"
echo "  npm run docker:compose:down          Stop services"
echo "  npm run docker:compose:ps            Show running services"
echo ""

echo "PRODUCTION COMMANDS:"
echo "  npm run production:start             Start all services"
echo "  npm run production:stop              Stop all services"
echo "  npm run production:logs              View logs"
echo "  npm run production:health            Health check"
echo "  npm run production:monitor           Monitor dashboard"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "🚨 EMERGENCY PROCEDURES"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

echo "IF MIGRATION FAILS:"
echo "━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. Check logs:"
echo "     npm run production:logs"
echo ""
echo "  2. List available backups:"
echo "     npm run migration:rollback -- --list"
echo ""
echo "  3. Rollback to previous state:"
echo "     npm run migration:rollback -- backup_file.sql"
echo ""
echo "  4. Restart services:"
echo "     npm run production:start"
echo ""

echo "IF APPLICATION CRASHES:"
echo "━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1. View logs:"
echo "     npm run production:logs"
echo ""
echo "  2. Check service status:"
echo "     npm run docker:compose:ps"
echo ""
echo "  3. Restart specific service:"
echo "     docker restart driver_booking_app_prod"
echo ""
echo "  4. If still down, full restart:"
echo "     npm run production:stop"
echo "     npm run production:start"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "📁 FILE STRUCTURE"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTATION"
echo "  ├── PRISMA_PRODUCTION_GUIDE.md         ← START HERE"
echo "  ├── DEPLOYMENT_CHECKLIST.md"
echo "  ├── DEPLOYMENT_GUIDE.sh"
echo "  ├── PRODUCTION_DEPLOYMENT_SUMMARY.md"
echo "  └── scripts/README.md"
echo ""
echo "⚙️  CONFIGURATION"
echo "  ├── Dockerfile.production"
echo "  ├── docker-compose.production.yml"
echo "  ├── dockploy.yml"
echo "  └── .env.production.example"
echo ""
echo "🔧 SCRIPTS (Executable)"
echo "  ├── scripts/pre-migration.sh"
echo "  ├── scripts/apply-migration.sh"
echo "  ├── scripts/rollback-migration.sh"
echo "  └── scripts/monitor-migration.sh"
echo ""
echo "🌱 DATABASE"
echo "  ├── prisma/schema.prisma"
echo "  ├── prisma/seed.ts"
echo "  └── prisma/seed-production.ts"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "✅ CHECKLIST"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "BEFORE DEPLOYMENT:"
echo "  ☐ Copy .env.production.example to .env.production"
echo "  ☐ Fill in actual database credentials"
echo "  ☐ Set secure admin password"
echo "  ☐ Test database connection"
echo "  ☐ Review all migration files"
echo "  ☐ Backup existing database"
echo "  ☐ Notify team about deployment"
echo ""

echo "DURING DEPLOYMENT:"
echo "  ☐ Run pre-migration checks"
echo "  ☐ Apply migrations"
echo "  ☐ Seed database"
echo "  ☐ Build Docker image"
echo "  ☐ Start services"
echo "  ☐ Run health checks"
echo ""

echo "AFTER DEPLOYMENT:"
echo "  ☐ Monitor logs for errors"
echo "  ☐ Test API endpoints"
echo "  ☐ Verify database seeding"
echo "  ☐ Test application functionality"
echo "  ☐ Document deployment"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "💡 TIPS & BEST PRACTICES"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

echo "✅ DO:"
echo "  • Always run pre-migration checks first"
echo "  • Create backup before migrations"
echo "  • Test on staging before production"
echo "  • Monitor logs after deployment"
echo "  • Keep 30 days of backups"
echo ""

echo "❌ DON'T:"
echo "  • Edit migration files after deploying"
echo "  • Run prisma reset in production"
echo "  • Delete backups without archiving"
echo "  • Skip pre-migration validation"
echo "  • Deploy without backups"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "🎉 ANDA SIAP UNTUK PRODUCTION DEPLOYMENT!"
echo ""
echo "Dokumentasi lengkap tersedia di:"
echo "  • Read: PRISMA_PRODUCTION_GUIDE.md"
echo "  • Reference: DEPLOYMENT_CHECKLIST.md"
echo "  • Scripts: scripts/README.md"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
